name: Deploy Backend UTSCLOUD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        env:
          # Sekarang env diletakkan sejajar dengan uses, bukan di dalam with
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Deploy to Private Backend via Nginx Proxy
        uses: appleboy/ssh-action@v1.0.3
        with:
          # 1. Konfigurasi Target Akhir (Server Backend)
          host: ${{ secrets.BACKEND_HOST }}
          username: ubuntu
          key: ${{ secrets.BACKEND_PRIVATE_KEY }}
          port: 22

          # 2. Konfigurasi Jembatan (Server Nginx / Jump Host)
          proxy_host: ${{ secrets.NGINX_HOST }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.NGINX_PRIVATE_KEY }}
          proxy_port: 22

          # 3. Instruksi yang dijalankan di Server Backend
script: |
  cd ~/health/UTSCLOUD

  # 1. Ambil semua perubahan terbaru dari GitHub tanpa merge
  git fetch --all

  # 2. PAKSA kode di server sama dengan branch main (menghapus editan lokal di server)
  git reset --hard origin/main

  # 3. Perbaiki izin folder agar bisa menulis file .env
  sudo chown -R ubuntu:ubuntu ~/health/UTSCLOUD

  # 4. Update file .env
  echo "${{ secrets.ENV_CONTENT }}" > .env

  # 5. Jalankan Docker
  sudo docker-compose down
  sudo docker-compose up -d --build
  sudo docker image prune -f
